name: Python Package Release

on:
  push:
    tags:
      - 'v*.*.*'  # 触发工作流的标签格式，遵循语义版本控制
      - 'v*.*.*alpha*'  # 匹配预发布版本
      - 'v*.*.*beta*'  # 匹配预发布版本
      - 'v*.*.*rc*'  # 匹配预发布版本

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
      - name: Publish package distributions to PyPI
        run: pdm publish